language: cpp
compiler:
  - clang
notifications:
  email: false
before_install:
  - "export DISPLAY=:99.0"                                         # Required for graphics
  - "sh -e /etc/init.d/xvfb start"                                 # Required for graphics
  - wget https://julialang.s3.amazonaws.com/bin/linux/x64/0.3/julia-0.3.2-linux-x86_64.tar.gz
  - tar -xzvf julia-0.3.2-linux-x86_64.tar.gz
  - /home/travis/build/codles/APES.jl/julia-8227746b95/bin/julia -e 'Pkg.clone("https://github.com/codles/APES.jl.git")'
  - /home/travis/build/codles/APES.jl/julia-8227746b95/bin/julia -e 'Pkg.update()'       # Required for Tk to work
  # - /home/travis/build/codles/APES.jl/julia-8227746b95/bin/julia -e 'Pkg.build("APES")'  # Required for Tk to work
script:
  - /home/travis/build/codles/APES.jl/julia-8227746b95/bin/julia -e 'Pkg.test("APES")'

